spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/products
        filters:
        - PrefixPath=/api/v1
        - AddResponseHeader=X-powered-by, Gateway-Service
      
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/orders
        filters:
        - PrefixPath=/api/v1
        - AddResponseHeader=X-powered-by, Gateway-Service
        
      - id: discovery-service
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/
              
      - id: discovery-service-static
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/**
                  
              
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
   
logging:
  level:
    '[org.springframework.cloud.gateway]': trace
      
